export const StateType = freeze({
	Title:    0,
	Attract:  1,
	Start:    2,
	Restart:  3,
	NewLevel: 4,
	Ready:    5,
	Playing:  6,
	Clear:    7,
	FlashMaze:8,
	CoffBrk:  9,
	Crashed: 10,
	Losing:  11,
	GameOver:12,
	Quit:    13,
})