'src/_lib/__util.js'
'src/_lib/_extjq.js'
'src/_lib/astar.js'
'src/_lib/canvas.js'
'src/_lib/direction.js'
'src/_lib/mouse.js'
'src/_lib/state.js'
'src/_lib/rand.js'
'src/_lib/rect.js'
'src/_lib/timer.js'
'src/_lib/vec2.js'

'src/_snd/_loader.js'
'src/_snd/sound.js'
'src/_snd/speaker.js'

'src/_constants.js'
'src/_param.js'
'src/_main.js'
'src/ui.js'
'src/scene.js'
'src/score.js'
'src/lives.js'
'src/points.js'

'src/maze.js'
'src/wall.js'

'src/actor.js'

'src/pacman/pac.js'
'src/pacman/pac_sprite.js'
'src/pacman/losing.js'

'src/ghosts/ghost.js'
'src/ghosts/ghost_sub.js'
'src/ghosts/ghost_sys.js'
'src/ghosts/ghost_sprite.js'
'src/ghosts/glow.js'

'style/main.css'
'style/form.css'
