'_lib/__util.js'
'_lib/_extjq.js'
'_lib/_canvas.js'
'_lib/confirm.js'
'_lib/direction.js'
'_lib/menu.js'
'_lib/mouse.js'
'_lib/state.js'
'_lib/timer.js'
'_lib/rect.js'
'_lib/vec2.js'

'_sprites/index.html'
'_sprites/_constants.js'
'_sprites/_main.js'
'_sprites/actor.js'
'_sprites/anime.js'
'_sprites/drag_scroll.js'
'_sprites/style.css'

'index.html'

'_snd/loader.js'
'_snd/sound.js'
'_snd/speaker.js'

'src/demo/_run_timer.js'
'src/demo/attract.js'
'src/demo/coffee_break.js'

'src/_constants.js'
'src/_map_data.js'
'src/_canvas.js'
'src/_menu.js'
'src/_main.js'
'src/_state.js'
'src/control.js'
'src/fruit.js'
'src/fruits_sprite.js'
'src/lives.js'
'src/maze.js'
'src/maze_wall.js'
'src/message.js'
'src/points.js'
'src/points_sprite.js'
'src/score.js'

'src/actor.js'
'src/pacman/pac.js'
'src/pacman/pac_sprite.js'
'src/pacman/pac_losing.js'

'src/ghosts/_system.js'
'src/ghosts/ghost.js'
'src/ghosts/ghost_sub.js'
'src/ghosts/ghost_sprite.js'
'src/ghosts/ghost_sprite_cb.js'
'src/ghosts/glow.js'
'src/ghosts/show_targets.js'

'styles/main.css'
'styles/ui.css'
'styles/config.css'
